name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: |
            docs/requirements-docs.txt
            pyproject.toml
            mkdocs.yml
            mkdocs.pt.yml

      - name: Install docs dependencies
        run: |
          python -m pip install -U pip
          pip install -r docs/requirements-docs.txt

      # Necess√°rio se o mkdocstrings importa seu pacote via src/
      - name: Install package (editable)
        run: |
          pip install -e .

      # Deploy EN (raiz /tucoopy/)
      - name: Deploy MkDocs (en)
        run: |
          mkdocs gh-deploy --force --config-file mkdocs.yml

      # Deploy PT (/tucoopy/pt/)
      - name: Deploy MkDocs (pt)
        run: |
          mkdocs gh-deploy --force --config-file mkdocs.pt.yml
